/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control.gui;

import control.Control;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel Marin
 */
public class Controles extends javax.swing.JFrame {

    private Control control;
    private String ruta;

    /**
     * Creates new form Controles
     */
    public Controles() {
        initComponents();
        bCalcular.setEnabled(false);
        bNuevo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bBuscarArchivo = new javax.swing.JButton();
        LNamePromedio = new javax.swing.JLabel();
        labelPromedio = new javax.swing.JLabel();
        LNameDesvEstandar = new javax.swing.JLabel();
        labelDesvEstandar = new javax.swing.JLabel();
        textRuta = new javax.swing.JTextField();
        bCalcular = new javax.swing.JButton();
        labelRuta = new javax.swing.JLabel();
        bIngresarRuta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bBuscarArchivo.setText("Buscar Archivo");
        bBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarArchivoActionPerformed(evt);
            }
        });

        LNamePromedio.setText("Promedio:");

        labelPromedio.setText("0");

        LNameDesvEstandar.setText("Desviación Estándar:");

        labelDesvEstandar.setText("0");

        textRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRutaActionPerformed(evt);
            }
        });

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        bIngresarRuta.setText("Ingresar Ruta");
        bIngresarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarRutaActionPerformed(evt);
            }
        });

        jLabel1.setText("Calculadora de Desviacion Estándar");

        bNuevo.setText("Nuevo Archivo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });

        jLabel2.setText("Escribir ruta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LNamePromedio)
                                    .addComponent(LNameDesvEstandar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(bBuscarArchivo)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelRuta)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelPromedio)
                                        .addComponent(labelDesvEstandar))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(textRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(bCalcular)
                        .addGap(35, 35, 35)
                        .addComponent(bNuevo)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bIngresarRuta)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBuscarArchivo)
                    .addComponent(labelRuta)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bIngresarRuta)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNamePromedio)
                    .addComponent(labelPromedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNameDesvEstandar)
                    .addComponent(labelDesvEstandar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCalcular)
                    .addComponent(bNuevo))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void bBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarArchivoActionPerformed

        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int resultado = selectorArchivos.showOpenDialog(this);
        if ((selectorArchivos.getSelectedFile() == null) || (selectorArchivos.getSelectedFile().getName().equals(""))) {
            textRuta.setText("");
        } else {
            ruta = selectorArchivos.getSelectedFile().getAbsolutePath();
            textRuta.setText(ruta);
        }
    }//GEN-LAST:event_bBuscarArchivoActionPerformed

    /**
     *
     * @param evt
     */
    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        bCalcular.setEnabled(false);
        try {
            control = new Control(ruta);
            mostrarResultados(control);
        }catch(FileNotFoundException fnfe){
            JOptionPane.showMessageDialog(null, fnfe.getMessage(), "ERROR", 0);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, nfe.getMessage(), "ERROR", 0);
        }
    }//GEN-LAST:event_bCalcularActionPerformed
    /**
     *
     * @param evt
     */
    private void bIngresarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarRutaActionPerformed
        if (textRuta.getText().length() == 0) {
            
        }else{
            bCalcular.setEnabled(true);
            bNuevo.setEnabled(true);

            bBuscarArchivo.setEnabled(false);
            bIngresarRuta.setEnabled(false);
            textRuta.setEnabled(false);
            
            ruta = textRuta.getText();
        }
    }//GEN-LAST:event_bIngresarRutaActionPerformed

    private void textRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRutaActionPerformed

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        bBuscarArchivo.setEnabled(true);
        bIngresarRuta.setEnabled(true);
        bCalcular.setEnabled(false);
        bNuevo.setEnabled(false);
        textRuta.setEnabled(true);
        ruta = "";
        textRuta.setText("");
        labelPromedio.setText("");
        labelDesvEstandar.setText("");
    }//GEN-LAST:event_bNuevoActionPerformed
    /**
     *
     * @param control
     */
    private void mostrarResultados(Control control) {

        labelPromedio.setText(String.format("%.2f", control.getPromedio()));
        labelDesvEstandar.setText(String.format("%.2f", control.getDesvEstandar()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LNameDesvEstandar;
    private javax.swing.JLabel LNamePromedio;
    private javax.swing.JButton bBuscarArchivo;
    private javax.swing.JButton bCalcular;
    private javax.swing.JButton bIngresarRuta;
    private javax.swing.JButton bNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDesvEstandar;
    private javax.swing.JLabel labelPromedio;
    private javax.swing.JLabel labelRuta;
    private javax.swing.JTextField textRuta;
    // End of variables declaration//GEN-END:variables
}
